/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 12
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_if = 2,
  anon_sym_while = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_program = 6,
  sym_expression = 7,
  sym_if_stat = 8,
  sym_while_stat = 9,
  sym_block = 10,
  aux_sym_program_repeat1 = 11,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_if] = "if",
  [anon_sym_while] = "while",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_program] = "program",
  [sym_expression] = "expression",
  [sym_if_stat] = "if_stat",
  [sym_while_stat] = "while_stat",
  [sym_block] = "block",
  [aux_sym_program_repeat1] = "program_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_program] = sym_program,
  [sym_expression] = sym_expression,
  [sym_if_stat] = sym_if_stat,
  [sym_while_stat] = sym_while_stat,
  [sym_block] = sym_block,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_stat] = {
    .visible = true,
    .named = true,
  },
  [sym_while_stat] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 2,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 13,
  [20] = 14,
  [21] = 15,
  [22] = 17,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 23,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'w') ADVANCE(4);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_if);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_while);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(27),
    [sym_expression] = STATE(3),
    [sym_if_stat] = STATE(14),
    [sym_while_stat] = STATE(14),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_if] = ACTIONS(7),
    [anon_sym_while] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(2),
    [sym_if_stat] = STATE(14),
    [sym_while_stat] = STATE(14),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(16),
    [anon_sym_while] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(2),
    [sym_if_stat] = STATE(14),
    [sym_while_stat] = STATE(14),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(22),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_if] = ACTIONS(7),
    [anon_sym_while] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(5),
    [sym_if_stat] = STATE(20),
    [sym_while_stat] = STATE(20),
    [aux_sym_program_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(24),
    [anon_sym_if] = ACTIONS(26),
    [anon_sym_while] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(30),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(7),
    [sym_if_stat] = STATE(20),
    [sym_while_stat] = STATE(20),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(24),
    [anon_sym_if] = ACTIONS(26),
    [anon_sym_while] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(32),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(8),
    [sym_if_stat] = STATE(20),
    [sym_while_stat] = STATE(20),
    [aux_sym_program_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(24),
    [anon_sym_if] = ACTIONS(26),
    [anon_sym_while] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(34),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(7),
    [sym_if_stat] = STATE(20),
    [sym_while_stat] = STATE(20),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(36),
    [anon_sym_if] = ACTIONS(39),
    [anon_sym_while] = ACTIONS(42),
    [anon_sym_RBRACE] = ACTIONS(11),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(7),
    [sym_if_stat] = STATE(20),
    [sym_while_stat] = STATE(20),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(24),
    [anon_sym_if] = ACTIONS(26),
    [anon_sym_while] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_if,
    ACTIONS(9), 1,
      anon_sym_while,
    STATE(23), 1,
      sym_expression,
    STATE(14), 2,
      sym_if_stat,
      sym_while_stat,
  [17] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_if,
    ACTIONS(9), 1,
      anon_sym_while,
    STATE(24), 1,
      sym_expression,
    STATE(14), 2,
      sym_if_stat,
      sym_while_stat,
  [34] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_if,
    ACTIONS(9), 1,
      anon_sym_while,
    STATE(26), 1,
      sym_expression,
    STATE(14), 2,
      sym_if_stat,
      sym_while_stat,
  [51] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_if,
    ACTIONS(9), 1,
      anon_sym_while,
    STATE(25), 1,
      sym_expression,
    STATE(14), 2,
      sym_if_stat,
      sym_while_stat,
  [68] = 2,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(49), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [78] = 2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(53), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [88] = 2,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(57), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [98] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(61), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [108] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(65), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [118] = 2,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [127] = 2,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [136] = 2,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [145] = 2,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [154] = 2,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_while,
  [163] = 2,
    ACTIONS(67), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_block,
  [170] = 2,
    ACTIONS(67), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_block,
  [177] = 2,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
  [184] = 2,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_block,
  [191] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 17,
  [SMALL_STATE(11)] = 34,
  [SMALL_STATE(12)] = 51,
  [SMALL_STATE(13)] = 68,
  [SMALL_STATE(14)] = 78,
  [SMALL_STATE(15)] = 88,
  [SMALL_STATE(16)] = 98,
  [SMALL_STATE(17)] = 108,
  [SMALL_STATE(18)] = 118,
  [SMALL_STATE(19)] = 127,
  [SMALL_STATE(20)] = 136,
  [SMALL_STATE(21)] = 145,
  [SMALL_STATE(22)] = 154,
  [SMALL_STATE(23)] = 163,
  [SMALL_STATE(24)] = 170,
  [SMALL_STATE(25)] = 177,
  [SMALL_STATE(26)] = 184,
  [SMALL_STATE(27)] = 191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stat, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stat, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_stat, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_stat, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fusion4(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fusion4",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
